.TH LEMIPC 1 "October 2023" "lemipc 1.0" "User Commands"
.SH NAME
lemipc \- The most funny and interactive game ever created!!!!
.SH SYNOPSIS
.B lemipc
[\fIOPTION\fR]...
.SH DESCRIPTION
\fBlemipc\fR is a program that does something interesting.

.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Display this help and exit.
.TP
\fB\-v\fR, \fB\-\-version\fR
Output version information and exit.
.TP
\fB team \fR
Joins a team. Valid teams are 0-9.

.SH EXAMPLES
.TP
\fBlemipc \-h\fR
Display the help message.

.SH AUTHOR
Written by Gemartin99 in colaboration with rpliego and jferrer-.
.SH COPYRIGHT
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.